version: '3.9'
services:
  pgdb:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
    ports:
      - '5432:5432'
    volumes:
      - pgvolume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: abc123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - '5050:80'

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgvolume:
